CREATE TABLE `initializedmodules` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`module` varchar(255) NOT NULL,
	`status` enum('INITIALIZED','DISABLED','NOTINITIALIZED') NOT NULL DEFAULT 'NOTINITIALIZED',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
