templates:
    - templatename: stuff
      nodetype: CATEGORY
      parameters:
          - type: ipe
            field: blurb
            label: Blurb
            tag: p
            rows: 4
      addable_objects: 
          - templateId: stuffItem 
            templateAddText: Add a Stuff

    - templatename: stuffItem
      nodetype: LEAF
      parameters:
          - type: ipe
            field: text
            label: Text
            tag: p
            rows: 4
          - type: ipe
            field: more
            label: MORE
            tag: p
            rows: 4
      allow_sort: true

    - templatename: home
      nodetype: LEAF
      parameters:
     
            
data:
    - templatename: stuff
      content:
          title: Stuff
    
    - templatename: home
      content:
          title: Home
    
